[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

[rpc_endpoints]
xlayer_testnet = "https://testrpc.xlayer.tech"
xlayer_mainnet = "https://rpc.xlayer.tech"

[etherscan]
xlayer_testnet = { key = "", url = "https://www.oklink.com/xlayer-testnet/api" }
